export { employeesService, type EmployeesService } from "./employees-service";
export { employeeKeys } from "./keys";
export { CAPABILITY_AVAILABILITY_CATALOG } from "./fixtures";
export { DEFAULT_CONFIGURATION } from "./defaults";
export {
  UNSUPPORTED_ACTION_HINT,
  UNSUPPORTED_MESSAGE,
  type EmployeesBackendSupport,
} from "./support";
export {
  ACTIVITY_KINDS,
  AUTONOMY_LEVELS,
  CAPABILITY_AVAILABILITY,
  CAPABILITY_GRANT_STATUS,
  EMPLOYEE_ACCENTS,
  EMPLOYEE_CAPABILITIES,
  EMPLOYEE_GLYPHS,
  EMPLOYEE_PERMISSIONS,
  EMPLOYEE_ROLES,
  EMPLOYEE_STATUS,
  EMPLOYEE_STATUS_LABEL,
  EMPLOYEE_STATUS_TONE,
  EMPLOYEE_TONES,
  EmployeeError,
  PERMISSION_DEFAULT_LEVEL,
  PERMISSION_LEVELS,
  PERMISSION_LEVEL_LABEL,
  PERMISSION_REQUIRES,
  PERMISSION_TONE,
  PLATFORM_GRANTS,
  isCapability,
  type ActivityKind,
  type AutonomyLevel,
  type CapabilityAvailability,
  type CapabilityGrantStatus,
  type EmployeeAccent,
  type EmployeeActivityEvent,
  type EmployeeAssignment,
  type EmployeeAssignments,
  type EmployeeCapability,
  type EmployeeCapabilityState,
  type EmployeeConfiguration,
  type EmployeeCurrentTask,
  type EmployeeDetail,
  type EmployeeDraft,
  type EmployeeErrorCode,
  type EmployeeGlyph,
  type EmployeeMemorySummary,
  type EmployeePermission,
  type EmployeePermissionId,
  type EmployeeQueueItem,
  type EmployeeRole,
  type EmployeeStatus,
  type EmployeeSummary,
  type EmployeeTemplate,
  type EmployeeTemplateSummary,
  type EmployeeTone,
  type EmployeesAdapter,
  type PermissionLevel,
  type PlatformGrant,
  type Sequence,
} from "./types";
