/**
 * Public surface of the conversations service. Features import from here and
 * never from the adapter or fixtures directly — the seam Sprint 18 swaps.
 */
export { conversationService, type ConversationService } from "./conversation-service";
export { conversationKeys } from "./keys";
export {
  CONVERSATION_TAGS,
  EMPLOYEE_LIST,
  EMPLOYEES,
  OWNER,
} from "./fixtures";
export {
  ATTACHMENT_KINDS,
  ATTACHMENT_KIND_LABEL,
  CONVERSATION_ARTIFACT_KINDS,
  CONVERSATION_ARTIFACT_KIND_LABEL,
  CONVERSATION_STATUSES,
  CONVERSATION_STATUS_LABEL,
  CONVERSATION_STATUS_TONE,
  ConversationError,
  EMPTY_SEARCH_QUERY,
  MESSAGE_CHANNELS,
  MESSAGE_KINDS,
  MESSAGE_ROLES,
  MESSAGE_ROLE_LABEL,
  READ_STATUSES,
  READ_STATUS_LABEL,
  SEARCH_SCOPES,
  SEARCH_SCOPE_LABEL,
  SUGGESTION_KINDS,
  SUGGESTION_KIND_LABEL,
  type ApprovalPayload,
  type ArtifactPayload,
  type Attachment,
  type AttachmentKind,
  type ConversationActionInput,
  type ConversationActionReceipt,
  type ConversationApprovalDecision,
  type ConversationArtifactKind,
  type ConversationDetail,
  type ConversationDraft,
  type ConversationErrorCode,
  type ConversationMessage,
  type ConversationSearchQuery,
  type ConversationSearchResult,
  type ConversationStatus,
  type ConversationSummary,
  type ConversationsAdapter,
  type EmployeeRef,
  type MemoryRef,
  type MessageChannel,
  type MessageKind,
  type MessageRole,
  type NotificationPayload,
  type OutgoingMessage,
  type Participant,
  type PinnedItem,
  type ReadStatus,
  type SearchScope,
  type SendReceipt,
  type Suggestion,
  type SuggestionKind,
  type TaskRef,
  type WorkflowRef,
} from "./types";
